### ISSUE TITLE
'Section' object has no attribute 'uid'

### ISSUE THREAD

**Issue by alexmaehon** [ffreemt/epub2txt#1]
from epub2txt import epub2txt

# from a local epub file
filepath = "xxx.epub"
res = epub2txt(filepath)

error:
[W 220424 15:25:32 epub2txt:98]  toc_uids exc: 'Section' object has no attribute 'uid'

**Comment by ffreemt** [comment]
It's just warning, perhaps the epub book is unconventional, it does not have any uid.

epub2txt just makes use of  the `ebooklib` package and is quite simple -- its main body has a dozen lines of code excluding error checking etc. Feel free to take a look.
