### ISSUE TITLE
httpx 0.16.1 which is incompatible.

### ISSUE THREAD

**Issue by novvoo** [ffreemt/epub2txt#4]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googletrans 4.0.0rc1 requires httpx==0.13.3, but you have httpx 0.16.1 which is incompatible.

**Comment by ffreemt** [comment]
That's because googletrans 4.0.0rc1 requires a lower version of httpx==0.13.3.
You can probably just ignore that. I tried to remove the version of httpx in the new versino of epub2txt. Hence you can also try to upgrade epub2txt.
